name: dependency-parser
description: Keeps the peer dependencies of your project up-to-date
author: Christian Knauf
inputs:
  package-json-path:
    description: The relative path of the package.json file of the project to update
    default: .
    required: true
  allowed-major-versions:
    description: Number of major versions allowed to downgrade
    default: '2'
    required: false
  allowed-minor-versions:
    description: Number of minor versions allowed per major version
    default: '10'
    required: false
  allow-pre-releases:
    description: Allow dependencies with pre-release versions (e.g. beta versions)
    default: 'false'
    required: false
  keep-versions:
    description: Keep the versions specified in package.json
    default: 'false'
    required: false
runs:
  using: node20
  main: 'dist/unattended/index.js'
