name: dependency-parser
description: Keeps the peer dependencies of your project up-to-date
author: Christian Knauf
inputs:
  # Core options
  base-branch:
    description: The base branch of the repository
    default: main
    required: true
  repo-token:
    description: The GITHUB_TOKEN secret
    required: true
  package-json-path:
    description: The path of the package.json file of the project to update
    default: ./
    required: true
  # Dependency parser options
  # TODO
runs:
  using: node20
  main: 'dist/unattended/index.js'
