name: "Dependency Parser Example"
on:
  push

jobs:
  parseDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Update peer dependencies
        uses: chrisKx0/dependency-parser@main
        with:
          allow-pre-releases: true
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
